<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Bunit" />
		<Using Include="Bunit.TestDoubles" />
		<Using Include="Microsoft.Extensions.DependencyInjection" />
		<Using Include="NUnit.Framework" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="bunit" Version="2.7.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="coverlet.collector" Version="6.0.3">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Syncfusion.Blazor.Grid" Version="33.2.3" />
		<PackageReference Include="Syncfusion.Blazor.Themes" Version="33.2.3" />
	</ItemGroup>



	<ItemGroup>
		<PackageReference Include="NUnit" Version="4.3.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
	</ItemGroup>



	<ItemGroup>
	  <ProjectReference Include="..\BlazorApp\BlazorApp.csproj" />
	</ItemGroup>


</Project>
