<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.14" PrivateAssets="all" />
    <PackageReference Include="Syncfusion.Blazor" Version="33.1.44" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="33.1.49" />
  </ItemGroup>

  <!-- Exclude test sources located in the tests folder from the Blazor app compilation -->
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

</Project>
